apiVersion: v1
kind: ConfigMap
metadata:
  name: catalog-service-config
  namespace: ecommerce
data:
  ServiceName: "Catalog Service"
  ApiPathBase: "catalog-service"
  ASPNETCORE_ENVIRONMENT: "Development"