apiVersion: v1
kind: Service
metadata:
  name: catalog-service
  namespace: ecommerce
  labels:
    app: catalog-service
    app.kubernetes.io/name: catalog-service
spec:
  selector:
    app: catalog-service
    app.kubernetes.io/name: catalog-service
  ports:
    - protocol: TCP
      name: http
      port: 8080
      targetPort: 8080