apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name }}
  namespace: {{ .Values.namespace.name }}
data:
  ServiceName: "Catalog Service"
  ApiPathBase: "catalog"
  ASPNETCORE_ENVIRONMENT: "Development"