apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name }}
  namespace: {{ .Values.namespace.name }}
data:
  ServiceName: "Notification Service"
  ApiPathBase: "notification"
  ASPNETCORE_ENVIRONMENT: "Development"