apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.namespace.name }}
  labels:
    app: {{ .Values.service.name }}
    app.kubernetes.io/name: {{ .Values.service.name }}
spec:
  selector:
    app: {{ .Values.service.name }}
    app.kubernetes.io/name: {{ .Values.service.name }}
  ports:
    - protocol: TCP
      name: http
      port: 8080
      targetPort: 8080