apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauth2-proxy
  namespace: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oauth2-proxy
  template:
    metadata:
      labels:
        app: oauth2-proxy
    spec:
      containers:
      - name: oauth2-proxy
        image: quay.io/oauth2-proxy/oauth2-proxy:v7.12.0
        env:
          - name: OAUTH2_PROXY_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: oauth2-proxy-secrets
                key: CLIENT_SECRET
          - name: OAUTH2_PROXY_COOKIE_SECRET
            valueFrom:
              secretKeyRef:
                name: oauth2-proxy-secrets
                key: COOKIE_SECRET
        args:
          - --provider=oidc
          - --oidc-issuer-url=http://keycloak.ecommerce.com/realms/ecommerce
          - --client-id=oauth-proxy
          - --client-secret=$(OAUTH2_PROXY_CLIENT_SECRET)
          - --email-domain=*
          - --cookie-secret=$(OAUTH2_PROXY_COOKIE_SECRET)
          - --skip-jwt-bearer-tokens=true
          - --set-authorization-header=true
          - --pass-access-token=true
          - --pass-basic-auth=false
          - --http-address=0.0.0.0:4180
        ports:
        - containerPort: 4180