apiVersion: v1
kind: Secret
metadata:
  name: oauth2-proxy-secrets
  namespace: ecommerce
type: Opaque
stringData:
  CLIENT_SECRET: STaeGO7WOW1h96vd2JwuezmDMs9pxBde
  COOKIE_SECRET: 2TCp0i6Xh20zZaIYdKZ1FS2XwlaB1qUWI1cvHHJlYoU=