apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  namespace: {{ .Values.namespace.name }}
  labels:
    app: {{ .Values.deployment.name }}
    app.kubernetes.io/name: {{ .Values.deployment.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.deployment.name }}
      app.kubernetes.io/name: {{ .Values.deployment.name }}
  replicas: {{ .Values.deployment.replicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.name }}
        app.kubernetes.io/name: {{ .Values.deployment.name }}
      annotations:
        linkerd.io/inject: enabled
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
      - name: {{ .Values.deployment.name }}
        image: {{ .Values.deployment.image }}:{{ .Values.deployment.tag }}
        imagePullPolicy: {{ .Values.deployment.imagePullPolicy }}
        ports:
          - containerPort: 8080
        env:
          - name: ASPNETCORE_ENVIRONMENT
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.configMap.name }}
                key: ASPNETCORE_ENVIRONMENT
          - name: ServiceName
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.configMap.name }}
                key: ServiceName
          - name: ApiPathBase
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.configMap.name }}
                key: ApiPathBase
          - name: PodName
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: PodIP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: postgres-secrets
                key: POSTGRES_USER
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-secrets
                key: POSTGRES_PASSWORD
          - name: Database__ConnectionString
            value: "Host=postgres;Port=5432;Database=OrderService;Username=$(POSTGRES_USER);Password=$(POSTGRES_PASSWORD)"
          - name: Tempo__URI
            value: "http://tempo.observability:4317"
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "500m"
