apiVersion: v1
kind: ConfigMap
metadata:
  name: order-service-config
  namespace: ecommerce
data:
  ServiceName: "Order Service"
  ApiPathBase: "order-service"
  ASPNETCORE_ENVIRONMENT: "Development"