apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: ecommerce
  labels:
    app: order-service
    app.kubernetes.io/name: order-service
spec:
  selector:
    app: order-service
    app.kubernetes.io/name: order-service
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 8080