apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: order-service-monitor
  namespace: observability  
  labels:
    release: kube-prometheus-stack 
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: order-service
  namespaceSelector:
    matchNames:
      - ecommerce
  endpoints:
    - port: http
      path: /metrics
      interval: 10s