repositories:
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts

releases:
  - name: kube-prometheus-crds
    namespace: observability
    chart: prometheus-community/kube-prometheus-stack
    version: 75.4.0
    installed: true
    disableValidation: true
    values:
      - installCRDs: true
      - prometheusOperator:
          enabled: false
      - prometheus:
          enabled: false
      - alertmanager:
          enabled: false
      - grafana:
          enabled: false
