repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts
  - name: grafana
    url: https://grafana.github.io/helm-charts

releases:
  - name: rabbitmq
    namespace: ecommerce
    chart: bitnami/rabbitmq
    version: 15.3.2
    createNamespace: true
    values:
      - auth:
          username: guest
          password: guest
        service:
          ports:
            amqp: 5672
            management: 15672

  - name: kube-prometheus-stack
    namespace: observability
    chart: prometheus-community/kube-prometheus-stack
    version: 75.4.0
    createNamespace: true
    values:
      - observability/prometheus/kube-prom-stack-values.yaml

  - name: loki
    namespace: observability
    chart: grafana/loki
    version: 6.30.1
    createNamespace: true
    values:
      - observability/loki/loki-values.yaml

  - name: promtail
    namespace: observability
    chart: grafana/promtail
    version: 6.17.0
    createNamespace: true
    values:
      - observability/promtail/promtail-values.yaml

  - name: tempo
    namespace: observability
    chart: grafana/tempo
    version: 1.23.2
    createNamespace: true
    values:
      - observability/tempo/tempo-values.yaml
