apiVersion: v1
kind: Namespace
metadata:
  name: ecommerce
  # annotations:
  #   config.linkerd.io/default-inbound-policy: deny
    
---

apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx