prometheus:
  prometheusSpec:
    scrapeInterval: 10s          
    evaluationInterval: 10s
    retention: 15d
    enableAdminAPI: true

prometheus-node-exporter:
  hostPort: 9200
  containerPort: 9200
  service:
    port: 9200
  hostRootFsMount:
    enabled: false
    mountPropagation: HostToContainer
    
alertmanager:
  enabled: true

grafana:
  adminUser: admin
  adminPassword: admin
  persistence:
    enabled: true
    size: 5Gi
  additionalDataSources:
    - name: Loki
      type: loki
      uid: loki
      access: proxy
      url: http://loki:3100
    - name: Tempo
      type: tempo
      uid: tempo
      access: proxy
      url: http://tempo:3200