apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: ecommerce
  labels:
    app: notification-service
    app.kubernetes.io/name: notification-service
spec:
  selector:
    app: notification-service
    app.kubernetes.io/name: notification-service
  ports:
    - protocol: TCP
      name: http
      port: 8080
      targetPort: 8080