name: CI/CD - Order Service

on:
  push:
    paths:
      - "OrderService/**"
      - ".github/workflows/build-order-service.yml"
  pull_request:
    paths:
      - "OrderService/**"
      - ".github/workflows/build-order-service.yml"

jobs:
  call-template:
    uses: ./.github/workflows/service-template.yml
    with:
      gitversion_config: OrderService/GitVersion.yml
      solution_path: OrderService/OrderService.sln
      unit_test_project: OrderService/OrderService.Application.Unit.Tests/OrderService.Application.Unit.Tests.csproj
      integration_test_project: OrderService/OrderService.Presentation.Integration.Tests/OrderService.Presentation.Integration.Tests.csproj
      docker_image: maiconghidolin/ecommerce-order-service
      dockerfile_path: OrderService/OrderService.Presentation/Dockerfile
      dockerfile_context_path: OrderService
