name: CI/CD - Order Service

on:
  push:
    paths:
      - "OrderService/**"
      - ".github/workflows/build-order-service.yml"
  pull_request:
    paths:
      - "OrderService/**"
      - ".github/workflows/build-order-service.yml"

permissions:
  contents: write
  packages: write
  pull-requests: write

jobs:
  build:
    uses: ./.github/workflows/service-template.yml
    with:
      gitversion_config: OrderService/GitVersion.yml
      solution_path: OrderService/OrderService.sln
      unit_test_project: OrderService/OrderService.Application.Unit.Tests/OrderService.Application.Unit.Tests.csproj
      integration_test_project: OrderService/OrderService.Presentation.Integration.Tests/OrderService.Presentation.Integration.Tests.csproj
      docker_image: maiconghidolin/ecommerce-order-service
      dockerfile_path: OrderService/OrderService.Presentation/Dockerfile
      dockerfile_context_path: OrderService
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

  # This will be replaced by Kargo
  # update-values:
  #   needs: build
  #   uses: ./.github/workflows/update-helm-values-template.yml
  #   with:
  #     service_name: order-service
  #     values_path: Kubernetes/environments/dev/order-service/values.yaml
  #     image_name: maiconghidolin/ecommerce-order-service
  #     image_tag: ${{ needs.build.outputs.image-tag }}
  #     pr_base_branch: main