name: CI/CD - Catalog Service

on:
  push:
    paths:
      - "CatalogService/**"
      - ".github/workflows/build-catalog-service.yml"
  pull_request:
    paths:
      - "CatalogService/**"
      - ".github/workflows/build-catalog-service.yml"

permissions:
  contents: write
  packages: write
  pull-requests: write

jobs:
  build:
    uses: ./.github/workflows/service-template.yml
    with:
      gitversion_config: CatalogService/GitVersion.yml
      solution_path: CatalogService/CatalogService.sln
      unit_test_project: CatalogService/CatalogService.Application.Tests/CatalogService.Application.Unit.Tests.csproj
      integration_test_project: CatalogService/CatalogService.Presentation.Integration.Tests/CatalogService.Presentation.Integration.Tests.csproj
      docker_image: maiconghidolin/ecommerce-catalog-service
      dockerfile_path: CatalogService/CatalogService.Presentation/Dockerfile
      dockerfile_context_path: CatalogService
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

  update-values:
    needs: build
    uses: ./.github/workflows/update-helm-values-template.yml
    with:
      service_name: catalog-service
      values_path: Kubernetes/environments/dev/catalog-service/values.yaml
      image_name: maiconghidolin/ecommerce-catalog-service
      image_tag: ${{ needs.build.outputs.image-tag }}
      pr_base_branch: main
