name: CI/CD - Notification Service

on:
  push:
    paths:
      - "NotificationService/**"
      - ".github/workflows/build-notification-service.yml"
  pull_request:
    paths:
      - "NotificationService/**"
      - ".github/workflows/build-notification-service.yml"

permissions:
  contents: write
  packages: write
  pull-requests: write

jobs:
  build:
    uses: ./.github/workflows/service-template.yml
    with:
      gitversion_config: NotificationService/GitVersion.yml
      solution_path: NotificationService/NotificationService.sln
      unit_test_project: NotificationService/NotificationService.Application.Unit.Tests/NotificationService.Application.Unit.Tests.csproj
      integration_test_project: NotificationService/NotificationService.Presentation.Integration.Tests/NotificationService.Presentation.Integration.Tests.csproj
      docker_image: maiconghidolin/ecommerce-notification-service
      dockerfile_path: NotificationService/NotificationService.Presentation/Dockerfile
      dockerfile_context_path: NotificationService
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

  # This will be replaced by Kargo
  # update-values:
  #   needs: build
  #   uses: ./.github/workflows/update-helm-values-template.yml
  #   with:
  #     service_name: notification-service
  #     values_path: Kubernetes/environments/dev/notification-service/values.yaml
  #     image_name: maiconghidolin/ecommerce-notification-service
  #     image_tag: ${{ needs.build.outputs.image-tag }}
  #     pr_base_branch: main