name: CI/CD - Catalog Service

on:
  push:
    paths:
      - "CatalogService/**"
      - ".github/workflows/build-catalog-service.yml"
  pull_request:
    paths:
      - "CatalogService/**"
      - ".github/workflows/build-catalog-service.yml"

jobs:
  build:
    uses: ./.github/workflows/service-template.yml
    with:
      gitversion_config: CatalogService/GitVersion.yml
      solution_path: CatalogService/CatalogService.sln
      unit_test_project: CatalogService/CatalogService.Application.Tests/CatalogService.Application.Unit.Tests.csproj
      integration_test_project: CatalogService/CatalogService.Presentation.Integration.Tests/CatalogService.Presentation.Integration.Tests.csproj
      docker_image: maiconghidolin/ecommerce-catalog-service
      dockerfile_path: CatalogService/CatalogService.Presentation/Dockerfile
      dockerfile_context_path: CatalogService
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
