name: Helm Chart Template

on:
  workflow_call:
    inputs:
      chartName:
        required: true
        type: string

permissions:
  contents: read
  packages: write

jobs:
  helm:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Setup Helm
      uses: azure/setup-helm@v4
      with:
        version: v3.15.4

    - name: Login to Helm Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | helm registry login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Package Helm Chart
      run: |
          cd Kubernetes/helm/${{ inputs.chartName }}
          helm package . --version 0.1.${{ github.run_number }} --app-version ${{ github.sha }}
          helm push ${{ inputs.chartName }}-*.tgz oci://ghcr.io/${{ github.repository_owner }}/helm-charts

    - name: Package Helm Chart
      run: |
        CHART_PATH=Kubernetes/helm/${{ inputs.chartName }}
        helm package $CHART_PATH --destination .helm-charts

    - name: Push Helm Chart to GHCR
      run: |
        helm push .helm-charts/${{ inputs.chartName }}-*.tgz oci://ghcr.io/${{ github.repository_owner }}/charts