namespace:
  name: "ecommerce"
deployment:
  name: "catalog-service"
  replicas: 1
  image: "maiconghidolin/ecommerce-catalog-service"
  tag: "0.0.1"
  imagePullPolicy: IfNotPresent
serviceAccount:
  name: "catalog-service-account"
configMap:
  name: "catalog-service-config"
service:
  name: "catalog-service"
